# Generated by Django 3.2 on 2021-04-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
