version: '3.7'
services:
  database:
    container_name: database
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=docker
    networks:
      - backend
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend
    environment:
      - "SPRING_DATASOURCE_PASSWORD=123"
      - "SPRING_DATASOURCE_USERNAME=wittano"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://database/docker"
      - "SPRING_JAP_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect"
networks:
  backend: