version: '3'
services:
  database:
    container_name: database
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=wittano
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=local
    networks:
      - network
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SPRING_DATASOURCE_PASSWORD=123"
      - "SPRING_DATASOURCE_USERNAME=wittano"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://database/local?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useUnicode=true&characterSetResults=utf8"
      - "SPRING_JAP_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect"
networks:
  network: { }