version: '3'
services:
  db:
    image: mysql:8
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'
    ports:
    - 6033:3306
  spring-boot:
    build: '.'
    expose:
      - 8080
    ports:
    - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - db
