# Generated by Django 3.2 on 2021-04-19 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_remove_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatName',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='auth.user'),
            preserve_default=False,
        ),
    ]
