# Generated by Django 3.2 on 2021-04-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
